goldbergyoni/nodebestpractices

- sections/errorhandling/useonlythebuiltinerror.md
Hey, I just noticed an incomplete function declaration 😁
> Fix incomplete function declaration for appError

- README.md
explictly -> explicitly
interpeter -> interpreter  
Prefering -> Preferring 
asyncronous -> asynchronous
Nowdays -> Nowadays
extremly -> extremely
> corrected typos in readme

- README.md
> Add myself as Contributor

- sections/errorhandling/asyncerrorhandling.md
- sections/errorhandling/failfast.md
- Fix "SyntaxError: Unexpected token throw"
- Update Joi example
Fixes #43
> Fixup a couple of code examples

- sections/projectstructre/breakintcomponents.md
Just cleaned up some of the grammar
> Clean up some grammar

- README.md
change the plural conjugation `ease` to the correct singular conjugation `eases`
> Tiny grammar fix in section 1.2

- sections/production/createmaintenanceendpoint.md
The current link does not actually link to a video. This commit will add a direct link to the video as well as a link to the slide deck.
> Update resources section

- sections/production/smartlogging.chinese.md
> smartlogging.chinese.md

- README.md
- sections/errorhandling/catchunhandledpromiserejection.md
- sections/errorhandling/centralizedhandling.md
- sections/errorhandling/shuttingtheprocess.md
- sections/errorhandling/testingerrorflows.md
- sections/errorhandling/usematurelogger.md
- sections/errorhandling/useonlythebuiltinerror.md
- sections/production/bestateless.md
- sections/production/createmaintenanceendpoint.md
self explanatory
Regards,
Allen
> prettify and unify the syntax

- sections/production/assigntransactionid.md
This code is not Nginx but Express
> Fix wrong copypasta

- writing-guidelines.md
@BrunoScheufler kindly revise? no need to perform vast editing, only bold grammar/language issues
> Our content writing manifest

- README.md
Updating existing and new sections.
Addresses #33  and #133
> update security best practices section

- README.md
Addressing @i0natan comments https://github.com/i0natan/nodebestpractices/pull/134#issuecomment-363692337
> docs(security): update regex section

- README.md
- sections/security/sessions.md
I would like to contribute to this project, so I have added to the security section with some information around leaving session middleware to it's default config.
Let me know any feedback or where else I can contribute! Thanks
> MINOR Added 6.21. Use cookies/sessions securely

- sections/errorhandling/documentingusingswagger.md
minor typo (advanced -> advance)
> Fix typo in documentingusingswagger.md

- README.md
Containing changes discussed [here](https://github.com/i0natan/nodebestpractices/issues/154)
> Updates for March 2018 maintenance list (chores)

- README.md
Make the markdown in README.md consistent:
1. Remove multiple spaces in between words
2. Remove periods at the end of paragraphs
3. Remove extra line breaks
4. Add line breaks where missing
5. Ensure three `<br>`s at the end of level 1 headings
6. Indent embedded HTML consistently
7. Indent JavaScript blocks consistently
> Fix spaces, periods and line breaks

- README.md
* Change total from 16 to 17 for `5.Going To Production Practices` in ToC.
> Update total for '5. Going To Production Practices' in ToC

- README.md
1. Update top badges with 
* best practices item count (53 as on Apr 23, 2018)
* last update date (last commit in April was on [Apr 23, 2018](https://github.com/i0natan/nodebestpractices/commit/14f508ba8c74aff4624f81c7b61881b1792449e0))
* Node.js version (latest LTS - 8.11 - was released on [Mar 29, 2018](https://nodejs.org/dist/latest-v8.x/))
2. Award flowers to contributors whose PRs were merged
@keyfoxth
@utkarshbhatt12
Closes #172.
> Service maintenance chores for April

- README.md
- sections/security/ormodmusage.md
This pull request is still in a stage of work-in-progress and will be completed in the next days. If you have any additions or suggestions, don't hesitate to comment!
> Security - Using an ORM/ODM library and validating input to prevent query injection and other attacks

- README.chinese.md
- README.md
Closes #209
Please merge this PR when _all_ of the maintenance items are done.
> July maintenance PR

- README.chinese.md
- README.korean.md
- README.md
> August maintenance

- README.md
@js-kyle I have updated the dead link in security section. This pr will close #240
> Dead link in security section updated

- sections/security/login-rate-limit.md
The sample in this file had unused and unexistent variables. So I fixed it and did a little linting.
> Fix sample code

- sections/errorhandling/operationalvsprogrammererror.md
Hi it's me again! I saw that this example is not using ES6 syntax at all, so I decided to update it and I'm waiting for your OK!
Regards
> ES6 Class Syntax refactor

- sections/security/dependencysecurity.md
> Fixing some typos in dependencysecurity.md

- README.md
- sections/security/saferedirects.md
https://github.com/i0natan/nodebestpractices/issues/247
> MINOR Prevent unsafe redirects

- README.brazilian-portuguese.md
Hello everyone!
I think we're ready to push some Brazilian-Portuguese documentation!
I translated the README.brazilian-portuguese.md up to section 4.
This is not so much, but we'll get better soon!
Please, feel free to tell me if something is missing or if I should do more before I push it!
> Brazilian portuguese

- sections/security/limitrequests.chinese.md
>  [chinese translation] add 6.2

- README.md
1. Update top badges with
* best practices item count (79 as on Nov 14, 2018)
* last update date (Nov 14, 2018)
* Node.js version (latest LTS - 10.13.0)
2. Add bio to the core team
Closes: https://github.com/i0natan/nodebestpractices/issues/268
> (chore) service maintenance tasks for October

- README.md
This adds a link to the Github issue where we are leading discussions around the performance section. Also removes the note about API practices - imo we should remove it since we aren't acively working on it any time soon (if that changes, we can of course re-add it)
> Updates to performance section

- README.md
> fixes a typo on 6.5

- sections/errorhandling/failfast.md
There was an extraneous space. I also updated functions syntax to follow the style guide referenced in other parts of this document. These functions could potentially be updated to es6 as well.
> Typo && Spacing

- README.md
> November 2018 chores

- README.md
Trying my hands on giving back to community.
Project structure Practices -> Project Structure Practices
See small case `s` vs capital case `S`
> Minor text change- lower case to title case

- README.chinese.md
- README.korean.md
- README.md
Although we didn't file an issue specifically, I used our template and worked on the tasks.
> December 2018 maintenance

- README.md
The repo introduction needs a little bit of improvement for readability, so I have proposed some changes. These won't be perfect either but lets use it as a point of discussion?
Mainly keen to improve this as it is often the first thing someone will read when visiting
> update introduction prose

- README.md
Very minor changes, such as removing unneeded capitalization
> minor readability changes to best practice names

- README.md
Fix some minor typos, grammar errors, and add a few links.
> Fix some typos and grammar errors, add a few links

- README.md
Small typo fix in the TL;DR of 4.1.
> typo fix at 4.1

- sections/security/secureserver.md
I read this page and saw a few grammar improvements, hopefully you like them.
> Grammar improvements to secureserver.md

- sections/security/commonsecuritybestpractices.md
Did not like that OWASP A7 only included 'use CSP, so updated that to reference more content from OWASP with some slight changes to reflect node, e.g use a template engine.
Made some slight changes to the content for grammar improvements
> Updates to commonsecuritybestpractices.md

- README.brazilian-portuguese.md
- README.md
Here we go friends!
Very soon we're going to have the complete README file translated to Brazilian Portuguese!
> Add sections 6 and 7 (in Brazilian Portuguese)

- README.brazilian-portuguese.md
- README.chinese.md
- README.korean.md
- README.md
- Update top badges with
1. best practices item count (81 as on Mar 10, 2019)
2. last update date (Mar 10, 2019)
3. Node.js version (latest LTS - 10.15.3)
- Ensure all translations are aligned with the English version
- Update 'thank you' stars & flowers
- Announce availability of BR translation in the news section!
Closes: #338
> Service Feb 2019 maintenance chores

- README.brazilian-portuguese.md
Fixed anchors for chapters 5, 6 and 7 at README.brazilian-portuguese.md
> Fixed Anchors at brazilian translation

- README.brazilian-portuguese.md
> Updated README.brazilian-portuguese.md

- README.brazilian-portuguese.md
In this sentence the "de" is incorrect.
> Removed the unnecessary de

- README.brazilian-portuguese.md
Hello again guys!
In this PR, I'm translating the **Latest Best Practices and News**, and some other details that I was missing! 😃
>  Translates the Latest Best Practices and News

- README.md
- sections/security/login-rate-limit.md
1. README add common technique description and remove non-maintained package link
1. Improve title and remove non-maintained package example
> 6.12 fix login rate limit - brute-force prevention

- README.brazilian-portuguese.md
- sections/performance/nativeoverutil.brazilian-portuguese.md
Translated some missing parts of README.brazilian-portuguese.md
And fixed typo at sections/performance/nativeoverutil.brazilian-portuguese.md pointed out by @marcelosdm 
Sorry took so long, was busy with college stuff.
:)
> translated missing parts of README and fixed typo

- README.chinese.md
- README.korean.md
- README.md
This PR adds all changes referenced in #352 
Closes #352
> March 2019 maintenance update

- sections/projectstructre/configguide.md
Better view for comment in JSON content
```json
{
// Warning
}
```
```js
{
// No warning
}
> Update configguide.md - Change from json view to js view

- sections/security/login-rate-limit.md
Add related code example with rate-limiter-flexible package.
> 6.12 add code example

- README.brazilian-portuguese.md
- README.md
- sections/errorhandling/documentingusingswagger.brazilian-portuguese.md
- sections/projectstructre/configguide.brazilian-portuguese.md
- sections/security/avoid_publishing_secrets.brazilian-portuguese.md
- sections/security/limitrequests.brazilian-portuguese.md
- sections/security/login-rate-limit.brazilian-portuguese.md
- sections/security/ormodmusage.brazilian-portuguese.md
- sections/testingandquality/avoid-global-test-fixture.brazilian-portuguese.md
I noticed that the BR version was behind the updates made on the main version, so I looked into all commits after that PR i made where I translated most of the sections, and updated the BR documents according to what the English ones were update.
Also fixed a small mistake at the main README.md where the badge said 82 when it should say 83.
> Updated BR version to keep up with the main version

- README.brazilian-portuguese.md
Updating the README.brazilian-portuguese.md translation according to recent changes in the main (english) README.md file.
> Updated section 3.4 on README.brazilian-portuguese.md

- README.brazilian-portuguese.md
- README.chinese.md
- README.korean.md
- README.md
(please squash the commits when merging, was using the Github GUI)
> May 2019 updates

- sections/security/expirejwt.md
https://github.com/i0natan/nodebestpractices/issues/383
> Add note about express-jwt-blacklist

- all-contributors.md
Couple more things needed to get the bot working on this test file. After I work out how to prepare the test file how we like it, I'll look at setting it up for the main contributors list (Please approve PR so I can merge)
> Add tags for all-contributors

- sections/projectstructre/breakintcomponents.japanese.md
Make new file
Translate to Japanese
> Create breakintcomponents.japanese.md 

- sections/errorhandling/asyncerrorhandling.md
- makes the Promises example more readable
- adds an async/await example
> Update code examples in asyncerrorhandling.md

- sections/errorhandling/useonlythebuiltinerror.md
Updated to address comments by @BrunoScheufler in #420.
> Make one paragraph explainer more readable

- README.korean.md
* Remove unnecessary lines
* Fix typo
* Translate Section 5
It was my mistake last time. Please review this.
Thanks!
> Korean translation

- README.md
Added Pino to the suggested loggers list (fastest one!)
> Update README.md - Added Pino to the suggested loggers list

- sections/errorhandling/usematurelogger.russian.md
Hi everyone. This PR removes original EN paragraph that was translated by @oshliaer
> Russian translation. Removed EN fragment

- .all-contributorsrc
I have been running this bot locally to debug this issue, I think this config should get it working for our repo to start testing.
> working all-contributors-bot config

- README.turkish.md
- sections/projectstructre/breakintcomponents.turkish.md
- sections/projectstructre/configguide.turkish.md
- sections/projectstructre/createlayers.turkish.md
- sections/projectstructre/separateexpress.turkish.md
- sections/projectstructre/wraputilities.turkish.md
the 1st page finish. 
For the comment: https://github.com/goldbergyoni/nodebestpractices/pull/391#issuecomment-520227887
> Turkish translation

- README.md
Fixes an issue where the link would redirect to another page (due to the i0natan bit, I guess).
> Fix absolute link redirecting

- .operations/writing-guidelines.md
> Patch writing guidelines

- .operations/.markdownlint.json
- README.md
addresses https://github.com/goldbergyoni/nodebestpractices/issues/552
> revert MD013 changes

- sections/errorhandling/usematurelogger.brazilian-portuguese.md
- sections/errorhandling/usematurelogger.chinese.md
- sections/errorhandling/usematurelogger.korean.md
- sections/errorhandling/usematurelogger.md
> Removed the bunyan as a suggested logger

- sections/projectstructre/configguide.md
> Added a bullet point on validating env vars at start-up

- README.spanish.md
Spanish translation until point 7.2 . I'm spanish native
> Spanish translation

- sections/errorhandling/apmproducts.md
> Improve wording

- sections/projectstructre/breakintcomponents.spanish.md
Original Blog Quotes are kept, translation in italics provided.
Images alt-text also changed.
> breakintcomponents.spanish remaining translations

- README.md
- sections/errorhandling/useonlythebuiltinerror.md
After re-reading the changes I made on the last PR, I felt like it needed more elaboration.
Hopefully, you'll find this more accurate.
> Elaborate on 2.2 (Use only built-in Error object)

- README.md
The code example for do and avoid was the same,
> Updated the code example

- sections/security/commonsecuritybestpractices.md
> Update with Encryption of PII Data

- sections/production/assigntransactionid.md
transaction Id -> transaction id
transaction-id -> transaction id
When calling other microservice -> ... microservices
> fix minor typos

- README.md
Added Polish flag at the top of the homepage section
> Add Polish flag

- README.md
I've been on a hiatus from the project for a while, and don't foresee
being able to come out of it soon-ish, owing to various personal
reasons. Till such a time as I'm unable to contribute actively, it's
best that I go emeritus and make space for new folks.
Thanks for having me aboard the rocketship! Ya'll have been a wonderful
team and a joy to work with. Sincere gratitude from the depth of my
heart to all the steering committee members, collaborators and
contributors! 🙏
Until next,
Here's to the next 50,000 stars! 🌟
> announcement: Move Sagir to SC Emeritus

- README.md
- sections/docker/image-tags.md
- sections/docker/lint-dockerfile.md
> 2x Docker drafts

- sections/examples/dockerfile/.dockerignore
- sections/examples/dockerfile/Dockerfile
- sections/examples/dockerfile/package.json
- sections/examples/dockerfile/src/app.ts
I quickly wrote an example project to show usage of the dockerfile. 
I used typescript to have a build step to illustrate multi-stage build. I used koa to change from express ;)
Please let me know what we could add (or contribute to the PR directly)
> Add an example project with dockerfile - 1st draft

- .operations/writing-guidelines.indonesia.md
im creating the translation in writing-guidelines.indonesia.md
> hey im creating a indonesia translation 

- sections/docker/avoid-build-time-secrets.chinese.md
add avoid-build-time-secrets.chinese.md
> [Chinese]add avoid-build-time-secrets.chinese.md

- README.spanish.md
En el presente commit se añade:
-Lista de contribuidores
-Traducción inicial de la sección 8, referente a Docker
-Estandarización de mensajes de "Volver arriba"
-Enlace de menús del archivo
> Update README.spanish.md: Contenido nuevo y fixes

- sections/performance/block-loop.spanish.md
- sections/performance/nativeoverutil.spanish.md
Hello!
I've just added the Spanish translation for the performance section. 
Any change needed let me know!
> Performance spanish translation

- README.md
Revise questionable terminology, i.e. blacklist/whitelist
https://tools.ietf.org/id/draft-knodel-terminology-00.html
> Revise blacklist/whitelist terminology

- sections/security/commonsecuritybestpractices.md
> Update `commonsecuritybestpractices.md` : improved layout

- README.md
fixed a typo on password algorithms
> fix: typo on password algorithms

- README.md
Fix typo in Japanese translation on line 29 (Janapense --> Japanese)
> Fix Japanese typo in README.md

- README.indonesian.md
A translation for Indonesian Language.
Progress:
> Add Indonesian translation

- sections/testingandquality/3-parts-in-name.md
> Align comment in testing/3 parts in name

- README.md
The description does not match the subject
> Fix `Read More` 8.12

- .github/update-date-in-last-update-badge.yml
- .github/update-last-update-badge.sh
- README.md
The current last update badge need to be updated manually, so I used dynamic badge that fetch from custom endpoint to get the last commit date in master
The code for the custom endpoint is [here](https://runkit.com/rluvaton/get-last-contribution-to-github-branch)
> WIP - use dynamic last update badge to update at real-time

- sections/performance/block-loop.md
- Fix Link [Event Loop Best Practices — NodeJS Event Loop Part 5]
> docs: Fix link 

- sections/errorhandling/returningpromises.md
Signed-off-by: Benjamin Udoh <benjaminudoh10@gmail.com>
> Fixed typo in returning promises doc

- .all-contributorsrc
- README.md
Reverts goldbergyoni/nodebestpractices#975
Accidentally added the wrong person https://github.com/goldbergyoni/nodebestpractices/pull/962#issuecomment-837317553 😅
> Revert "docs: add yjoe as a contributor"

- README.russian.md
https://github.com/goldbergyoni/nodebestpractices/pull/943 for the Russian version, potentially a duplicate
The opening bracket should have been put on the next line to show an example, which might lead to an error
> Function curly brackets wrong example fix

- .github/workflows/automerge-prs.yml
- .github/workflows/update-date-in-last-update-badge.yml
Used in my [TechPicks Archive](https://github.com/rluvaton/techpicks-archive)
https://github.com/goldbergyoni/nodebestpractices/pull/950#issuecomment-826148023
> add automerge to update-last-badge auto prs

- README.brazilian-portuguese.md
[FEAT] Add news Brazilian Portuguese translation
Rearrange section 4 items, same as english materia
> [FEAT] Add news Brazilian Portuguese translation

- README.japanese.md
It seems like that description and sample code are not match.
> Fix sample code in README.japanese.md

- README.basque.md
- README.md
Resovle https://github.com/goldbergyoni/nodebestpractices/issues/936
> #936 Resolve wrong code example in 3.3 in README

- sections/performance/block-loop.md
As issued in #1001, thank you @JFernando122 for reporting
> update quotes to follow the quotes template and added some content

- README.french.md
Last commit original (goldbergyoni/nodebestpractices@a9e633b7af101bdfa1abf15c629c73cff98cf314)
> Update french docs

- README.brazilian-portuguese.md
the word "que" in Portuguese is a relative pronoun that precedes something corresponding and is absent in the description of the practice
> spelling correction in the portuguese brazilian translation

- README.korean.md
The news in the Korean translation was an old version, so I translated it into a new version.
> docs: update news in korean translation

- README.md
I just stumbled across this repo - its great. Thank you for collating and maintaining such a valuable resource.
This is just a very small PR to make a sentence slightly more gender inclusive. I could only find one example of this, which suggests that you are already thinking about this.
Thanks again for your great and useful work.
> docs: Change 'his' to gender neutral term 'their'

- README.md
The amount of content here has gotten quite long and is expected to keep growing. Hence, I think it's time to add the sub-sections to the table of contents. 
I know there is a `CTRl + F` thingy but I think sometimes you just want to look up the subtopics list and navigate to it for a quick refresher. Just me?
> Collapsible ToC for increased accessibility

- README.md
Reformatted part of code example in [3.3 Start a Codeblock's Curly Braces on the Same Line](https://github.com/goldbergyoni/nodebestpractices#-33-start-a-codeblocks-curly-braces-on-the-same-line) that needs to be avoided.
This solves issue #1116.
> Update code example 3.3

- README.md
> Add Josh-Hemphill to steering committee

- sections/errorhandling/shuttingtheprocess.md
Updated the Blog quote format from 'JS Recipes' in shuttingtheprocess.md to keep it uniform with other quotes.
> Updated the formatting for the blog quotation

- README.md
> Add Raz Luvaton to steering committee

- sections/testingandquality/refactoring.korean.md
- sections/testingandquality/refactoring.md
- sections/testingandquality/test-middlewares.korean.md
- sections/testingandquality/test-middlewares.md
- renamed the current files `refactoring.md` and `test-middlewares.md` to be the Korean version
- restored the original English content in those 2 files
fixes issue #1151 introduced with PR #1133
> Fix issue #1151

- README.brazilian-portuguese.md
Fixed the problem with curly braces
> fix the problem of the curly braces in the brazillian translation

- README.md
> fix(README.md): fix typo

- sections/docker/bootstrap-using-node.md
@all-contributors please add @moosashah for content
> chore: fix typo and link syntax

- README.md
- sections/errorhandling/testingerrorflows.md
- sections/production/lockdependencies.md
- sections/production/productioncode.md
- sections/projectstructre/choose-framework.md
No way to summarize this but a large set of edits to adapt to a new world with TypeScript, ESM, multiple frameworks and more
> Many modernizing edits 

- sections/drafts/readme-general-toc-4.md
> Fix typo in readme-general-toc-4.md

- README.md
- README.polish.md
I've fixed the code sample for 3.3
> 3.3 fix code sample

- README.md
> fix broken env-var broken link

- README.hebrew.md
This PR including about 50% of translation to Hebrew of the main readme page.
The layout (RTL) still need improvements and perhaps parts that already translated need another.
> Hebrew translation

- README.hebrew.md
- README.md
* add @hodbauer as a translator
* set readme.hebrew.md as a live reference
> Hebrew translation intro
