goldbergyoni/nodebestpractices

sections/errorhandling/catchunhandledpromiserejection.md
Based on @benjamingr comment, it's now mentioned that Unhandled rejections do warn
=> Unhandled rejections now do leave trace and warn

README.md
I believe a verb like "using" was accidentally dropped from 4.1, making the Postman description hard to parse.
=> Fix ambiguous typo in 4.1

README.md, sections/errorhandling/catchunhandledpromiserejection.md
* Format js code
* Quote the remaining paragaph from the blog post
* Remove unecessary text 'Close GIST window Skip to toolbar About WordPress'
=> [errorhandling] Format js code in the blog section

README.md
Parenthesis throw a syntax error when used like this with `class`
=> Removed parenthesis from SomeClassExample

README.md
The TLDR of [Carefully choose your CI platform](https://github.com/i0natan/nodebestpractices/blob/master/README.md#-43-carefully-choose-your-ci-platform-jenkins-vs-circleci-vs-travis-vs-rest-of-the-world) was coming up as a list, because there was a tab in front of it.
=> fix markdown in CI section

README.md
This PR proposes a small syntax fix for section `3.3 Start a Codeblock's Curly Braces in the Same Line`
=> Fix code sample syntax issue for bullet 3.3

sections/production/detectvulnerabilities.md
The mentioned article is only talking about nsp and not snyk.
I thought of maybe adding this article as well -
https://www.smashingmagazine.com/2016/01/eliminating-known-security-vulnerabilities-with-snyk/
And maybe this quote - 
> Running untrusted code inside your system poses a broad security risk. Tackling it isn’t simple, but a good place to start is by addressing known vulnerabilities. These are publicly disclosed security bugs, typically found and logged by users, or intentionally found and reported by security researchers. Being public makes these issues the easiest ones for attackers to find and exploit, and so very important to address.
> Right now, roughly 14% of the top npm packages carry known vulnerabilities. The stats are far worse for full applications: over 80% of Snyk …
=> Fixing #51

README.md
Added details about parameter binding support in typical database libraries, as ORM/ODM libraries are not the only options to protect against injections. Also included a sentence about explicitly avoiding template strings or string concatenation to create queries.
=> Expand 6.1 to include database libraries

README.md
1. Fix grammar and a typo in section '5.10. Measure and guard the memory usage'
2. Add a link to Walmart Node.js Memory Leak from Joyent blog for context
3. Trim trailing spaces at EoL in README.md
=> Fix grammar and typo in section 5.10

sections/security/avoideval.md
Dynamic execution of JavaScript also happens in new Function, which is even referenced here: https://github.com/i0natan/nodebestpractices#-615-avoid-javascript-eval-statements, so this should be included.
=> Include new Function within avoideval.md

README.md, sections/errorhandling/documentingusingswagger.md
Per @i0natan's request, I've added a small paragraph outlining the benefits of GraphQL for handling errors and data schemas in your APIs.
=> Add GraphQL mention to 2.5: "Document API errors..."

sections/security/ormodmusage.md
The previous landing page informed user to go to the GitHub where the cheatsheet has been moved to
=> Update the URL link

sections/errorhandling/centralizedhandling.brazilian-portuguese.md, sections/errorhandling/centralizedhandling.chinese.md, sections/errorhandling/centralizedhandling.md
Fix a small typo that can cause a real application to crash or don't work as expected.
An `err` object is passed to `logger.logError(err)` but the function argument is named `error`.
=> fix: Typo in centralizedhandling.md files

README.md
Fixes #26.
I hope I integrated all feedback from this issue, while leaving the core message intact: People should be aware how statements are separated or linked together, and that there are cases where ASI and/or semicolon do not help, if statement termination is not understood. This also leaves room for the reader to prefer semicolons or not.
=> Rename 3.4 Use Semicolon to proper statement separation

sections/errorhandling/usematurelogger.md
Related with #448
Count of lines in all files (EN-RU) must match. Probably a new line is superfluous in the original file.
There are
- missing uppercase letter `see example below. (3) watch and filter`
- newline `software\n (4) Expose`
- missing dot `intelligence tools like Splunk.`
=> Small typos

README.brazilian-portuguese.md, README.korean.md, README.md
The #454 was marked as `translation`. It seems #105 is out of date now.
=> Change the link of Russian progress to an active discussion

README.brazilian-portuguese.md
Termo async estava escrito de forma incorreta.
Term async was misspelled.
=> correção de termo 'acync' para 'async'

README.spanish.md
I changed some of the words and phrasing to make it more appealing to hispanic readers, this way it doesnt sound like it was translated but natively written on spanish
=> Spanish translation

README.md
The 7th section link is broken, this commit fixes it.
=> [Readme] link 7 point heading section properly

sections/errorhandling/asyncerrorhandling.md, sections/errorhandling/catchunhandledpromiserejection.md, sections/errorhandling/centralizedhandling.md, sections/errorhandling/failfast.md, sections/errorhandling/operationalvsprogrammererror.md, sections/errorhandling/shuttingtheprocess.md, sections/errorhandling/testingerrorflows.md, sections/errorhandling/usematurelogger.md, sections/errorhandling/useonlythebuiltinerror.md, sections/projectstructre/separateexpress.md
This PR adds typescript examples to the infrastructure and error handling sections.
I've formatted the code as proposed in #579 
If that style suits everyone I will add examples to the other sections too.
I've had to add `<br/>` to get linebreaks to appear in the `<pre>` block on github.
=> Add typescript examples for error handling and project structure

sections/errorhandling/useonlythebuiltinerror.brazilian-portuguese.md, sections/errorhandling/useonlythebuiltinerror.chinese.md, sections/errorhandling/useonlythebuiltinerror.korean.md, sections/errorhandling/useonlythebuiltinerror.md, sections/errorhandling/useonlythebuiltinerror.russian.md
[`__proto__`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto) is deprecated and shouldn't be used to set object prototype.
=> refactor: replace deprecated __proto__ in built-in Error example

README.md, sections/production/installpackageswithnpmci.md
Hi there,
I added a section about the use of npm ci.
I thought it would be better to put it right after the bullet point about locking dependencies.
Let me know what you think of it.
=> docs: Add a section about using npm ci

README.md
Hey, it doesn't look like winston and bunyan are particularly updated. Bunyan hasn't been updated in ~3 years for example.
The list should also mention somewhere that it's important to log to stdout and persist with another process.
CC @goldbergyoni
=> Remove unmaintained loggers and recommend pino first

README.spanish.md
Hello everyone,
I have read the front page and noticed some typos and errors in the current translation, I'll provide some information justifying each proposed change.
1. Practicas: [Typo](https://dle.rae.es/pr%C3%A1ctico), considering the other ocurrences have proper accute accent.
2. múltples: [Typo](https://dle.rae.es/m%C3%BAltiple)
3. devpos: Typo, you usually see the devops word as is in spanish (you can look up 'devops jobs' as a reference)
4. elegantemento: [Typo](https://dle.rae.es/elegantemente) I also believe we might want to use a different word (I can't come up with one right now)
5. 'reiniciadora': That might be a word but we should use better technical ones, you can find different translations for process management tools so I just used what …
=> Improve spanish translations

README.md, sections/docker/multi_stage_builds.md
I've added another couple of simpler and more focused multi-stage Docker build examples, also one for the README itself as an intro.
=> Add more multi-stage build examples

README.md
Update the .dockerignore section with a link to the correct .md file.
=> Fix .dockerignore section link

sections/docker/clean-cache.md
The command is `npm cache clean --force`, not `npm clean cache --force`
=> Fix npm cache clean command

README.md
The word Zombie was missing in the description of BP 8.2
=> Add missing `zombie` word in 8.2 BP

README.md, sections/docker/multi_stage_builds.md
Also added the hint in chapter 5.19 to use the `npm ci` command in automated environments.
Maybe this should also be updated in the *in detail section* [Multi Stage Builds with Docker](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/docker/multi_stage_builds.md), but this example uses yarn, which would be `yarn install --frozen-lockfile` then. Ideally with a short explanation that both commands can be fine, depending which package manager you use.
=> Use npm ci command in Docker builds

README.brazilian-portuguese.md
Fix "Otherwise" word to "Caso contrário" in 3.4 topic of brazilian-portuguese README
=> fix brazilian-portuguese translation README 3.4 topic

sections/errorhandling/usematurelogger.md
@kevynb , @goldbergyoni @josh-hemphill - updated the detailed logging page to remove Winston (no longer a recommended best practice) in response to #684 and #791 discussions
=> Remove older, slower Winston from detailed logging page

sections/errorhandling/documentingusingswagger.md
Refer to OpenAPI instead of the earlier name of Swagger
=> Refer to OpenAPI

README.md
Adds missing `is` in section [4.13 Test your middlewares in isolation](https://github.com/goldbergyoni/nodebestpractices#-413-test-your-middlewares-in-isolation).
=> Fixes minor grammar issue

sections/docker/install-for-production.md
See https://docs.npmjs.com/cli/v6/commands/npm-cache, there is no command called `npm clean`
=> docs(install-for-production): fix npm cache cli example

sections/errorhandling/centralizedhandling.md
Fixing a typo in `centralizedhandling.md`
=> fix: typo in the docs

README.md, sections/docker/bootstrap-using-node.md
-Add missing period to e.g. (e.g -> e.g.) in line 550
-Add a missing apostrophe (end-users -> to end-user's) on line 642 and a missing period on the same line (a.k.a -> a.k.a.)
-Add a code quote to lines 710 and 712 to standardize the formatting of `NODE_ENV` (to match line 714) 
-Fix the markdown code quotes typo in the title of 8.2. on line 1126 ('node' command, avoid npm start -> `node` command, avoid `npm start`)
=> Fix typos in README.md

README.md
How do you propose that I should state that in case the readers use TS they should use the `@typescript-eslint/no-throw-literal` as it solve the regular rule limitation.
https://github.com/typescript-eslint/typescript-eslint/issues/1258
=> Add ESLint rule for throwing only error objects

sections/testingandquality/avoid-global-test-fixture.md
The test examples have some anti patterns 
> Anti Pattern: no separation, one bulk, harder to interpret
> 
> From [AAA](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/testingandquality/aaa.md#code-example--anti-pattern-no-separation-one-bulk-harder-to-interpret)
=> Update test example to follow the AAA rule

sections/security/escape-output.md
Improved markdown rendering to better match the blog quote
=> escape-output.md: Improved markdown rendering

README.chinese.md
from the origin english version : 'common security best practices', the chinese title and content should be translated to '通用安全最佳实践' instead of '通用安全最佳实际'
=> docs: fix typo in the 6.5 chapter of chinese version

README.md
In the main `README` description about dos and don'ts about curly braces positions. They are same leading to confusion
It is
```javascript
// Do
function someFunction() {
// code block
}
// Avoid
function someFunction() {
// code block
}
```
Should have been 
```javascript
// Do
function someFunction() {
// code block
}
// Avoid
function someFunction() 
{
// code block
}
```
=> do and avoid for curly braces are same

.github/workflows/update-date-in-last-update-badge.yml
when you update the master in your fork it will trigger the update badge action so I limited it to only run on this repo
I tested it by merging this branch to my fork’s master branch
=> ci: limit update last time updated badge only to the main repo

README.korean.md
There was a curly brace error in the code of the bad example in 3.3 in the Korean translation. I have corrected this part.
// 나쁜 예
function someFunction() {
// 코드 블록
}
↓ change
// 나쁜 예
function someFunction()
{
// 코드 블록
}
=> a curly brace error in the code of the bad example in 3.3 in the Korean translation.

.github/workflows/update-last-update-badge.sh
This is part of the migration to Docusarus that discussed here - #820, #939
All HTML tags must be closed in MDX (Docusarus uses MDX) so although `<img ..>` is valid in plain HTML is invalid in MDX (same for all void elements e.g `img`, `br`, etc...)
=> Fix(update last update badge): close the img tag the created

README.basque.md, README.indonesian.md, README.japanese.md, README.korean.md
Must have newlines before the HTML comments as Docusaurus will fail to build without it.
I assume that when they are right after the HTML the parsing done by Docusaurus thinks these comments are part of the HTML which will try to convert it into a React component which would fail the build as HTML comments in React are unsupported (instead of `` you need to do `{/* comment */}`)
=> migrate: update the html comments after the contributors list to have new line before them

README.brazilian-portuguese.md, sections/drafts/readme-general-toc-1.md, sections/drafts/readme-general-toc-3.md, sections/drafts/readme-general-toc-4.md
There were some links that were inside of HTML comments as I assume because they weren't exist
Replace those dead translation links with the original ones.
Apparently, even links in comments are been checked before run/build in Docusaurus
=> migrate: convert dead translation links to original links

README.brazilian-portuguese.md
Fix typo in README.brazilian-portuguese.md as requested in the issue #1035
=> Fix: typo 

README.md
Update variable naming convention to include `SCREAMING_CASE` for global variables and static class properties
closes: #1043
=> variable naming convention with screaming case

sections/testingandquality/3-parts-in-name.md
Fix: typo on 4.2 Include 3 parts in each test name
=> Fix: typo  on 4.2 Include 3 parts in each test name
